### PR TITLE
Fix minor doc issues and add more content

### PR DESCRIPTION
**Pull request by jbcrail**

### CODE REVIEW

**Comment by martindurant** [comment]
Would you mind taking this opportunity to rename the plugins using underscores rather than hyphens? That will presumably filter through to a few places.

**Comment by martindurant** [comment]
That was good, but I actually meant the opposite https://github.com/ContinuumIO/intake-solr/blob/master/intake_solr/__init__.py#L11 , https://github.com/ContinuumIO/intake-solr/blob/master/intake_solr/__init__.py#L38 :)

**Comment by jbcrail** [comment]
Oops. Do you mean make other plugins reflect your highlighted lines?

**Comment by martindurant** [comment]
No no! :)
The name of the project, and everything referring to it, should remain intake-solr (with a hyphen), but the plugins should be `solr_*`, so that they are valid python identifiers.
Sorry for not being clear, and this is my fault for not correcting it in the first place. I hope I didn't cost you much time.

**Comment by martindurant** [comment]
+1

**Review by martindurant — APPROVED** [review]

**Pull request merged**
